import { rq,rqList } from "../utils/request";
 
import {  resultDataType,resultListType,LISTPAGEART_TYPE } from "../utils/interface.uts"
//统一的请求响应结构体
export type ImageInfo = {
	path:string
}
export class api {
	//请求文章列表.
	public static  async getImageList<ImageInfo>(arg:UTSJSONObject):Promise<resultListType<ImageInfo>|null>{
		return rqList<ImageInfo>('/system/attachments/list2','GET',arg,true);
	}
}