import { rqList } from "../utils/request";
 
import {resultListType } from "../utils/interface.uts"
//统一的请求响应结构体
export class ImageInfo  {
	path:string=''
	constructor(path:string) { // 构造函数，参数newname 
		this.path = path;
	}
}
export class api {
	//请求文章列表.
	public static  async getImageList(arg:UTSJSONObject):Promise<resultListType<ImageInfo>|null>{
		return rqList('/system/attachments/list2','GET',arg,false,(o)=>{
				return new ImageInfo(o['path']! as string)
		});
	}
}